/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GPA_Calc;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oSikaNi iSraeL
 */
public class cGpa extends javax.swing.JFrame {
    
    int xMouse;
    int yMouse;
    
      DefaultTableModel model;
    

    /**
     * Creates new form cGpa
     */
    public cGpa() {
        initComponents();
        
        model =(DefaultTableModel) jTable1.getModel(); 
    }
    
    
    public float sumAll (){
                float rowsCount = jTable1.getRowCount();
                float sum =0;
                for (int i =0; i<rowsCount; i++){
                
                    sum = sum+Float.parseFloat((String) jTable1.getValueAt(i, 2));
                }
             
            
            
            return sum;
                    }
    
    public float cgpa(){
        
        float my_gpa = sumAll();
        int rowsCount = jTable1.getRowCount();
        
        float C_gpa =my_gpa/rowsCount;
    
         your_cgpa.setText(Float.toString(C_gpa));
        
        return 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sem = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        level = new javax.swing.JComboBox<>();
        gpa = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        ent = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        your_cgpa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cgpa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem.setBackground(new java.awt.Color(201, 244, 167));
        sem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sem.setForeground(new java.awt.Color(0, 0, 0));
        sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Semester 1", "Semester 2" }));
        sem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                semKeyPressed(evt);
            }
        });
        getContentPane().add(sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, 40));

        jButton1.setBackground(new java.awt.Color(186, 217, 198));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Trash_15px.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setIconTextGap(0);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        level.setBackground(new java.awt.Color(201, 244, 167));
        level.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        level.setForeground(new java.awt.Color(0, 0, 0));
        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "Level 100", "Level 200", "Level 300" }));
        level.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                levelKeyPressed(evt);
            }
        });
        getContentPane().add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 40));

        gpa.setBackground(new java.awt.Color(197, 237, 176));
        gpa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        gpa.setForeground(new java.awt.Color(0, 0, 0));
        gpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaActionPerformed(evt);
            }
        });
        gpa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gpaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                gpaKeyTyped(evt);
            }
        });
        getContentPane().add(gpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, 40));

        back.setBackground(new java.awt.Color(182, 214, 192));
        back.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back To_25px_1.png"))); // NOI18N
        back.setText("Back");
        back.setToolTipText("Go Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backKeyPressed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 100, 40));

        ent.setBackground(new java.awt.Color(192, 228, 186));
        ent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ent.setForeground(new java.awt.Color(0, 0, 0));
        ent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Checked_25px_2.png"))); // NOI18N
        ent.setText("Enter");
        ent.setToolTipText("Update Table");
        ent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entActionPerformed(evt);
            }
        });
        ent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entKeyPressed(evt);
            }
        });
        getContentPane().add(ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, 40));

        reset.setBackground(new java.awt.Color(186, 217, 198));
        reset.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 0));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Reset_15px.png"))); // NOI18N
        reset.setText("Reset");
        reset.setToolTipText("Reset Table");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        reset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resetKeyPressed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 90, 30));

        your_cgpa.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        your_cgpa.setForeground(new java.awt.Color(0, 0, 0));
        your_cgpa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Your CGPA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        getContentPane().add(your_cgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 320, 90));

        jTable1.setBackground(new java.awt.Color(201, 244, 167));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Level", "Semester", "GPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setOpaque(false);
        jTable1.setRowHeight(25);
        jTable1.setRowMargin(2);
        jTable1.setSelectionBackground(new java.awt.Color(182, 214, 192));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 600, 230));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("GPA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 110, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Semester");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Level");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        cgpa.setBackground(new java.awt.Color(202, 245, 166));
        cgpa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cgpa.setForeground(new java.awt.Color(0, 0, 0));
        cgpa.setText("CGPA");
        cgpa.setToolTipText("Calculate CGPA");
        cgpa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgpaActionPerformed(evt);
            }
        });
        getContentPane().add(cgpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 90, 40));

        jLabel2.setBackground(new java.awt.Color(201, 244, 167));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/background.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 620, 430));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("CGPA CACLUATOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 410, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logoNew.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 400, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_25px_8.png"))); // NOI18N
        jLabel8.setToolTipText("Exit");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 90));

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Menu_15px_1.png"))); // NOI18N
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/About_15px_2.png"))); // NOI18N
        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(620, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        start_Page sp = new start_Page();
        sp.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_jLabel8MouseClicked

    private void entActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entActionPerformed
        // TODO add your handling code here:
        
        
        if( level.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Level is not Selected");
        }
        
        else if(sem.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Semester is not Selected");
        }
        
        else if (gpa.getText().isEmpty()){
        
        
            JOptionPane.showMessageDialog(null, " Enter your GPA for the Semester");
        }
        
        else {
            
            double myGpa = Double.parseDouble(gpa.getText());
            
            if(myGpa >5.0){
            
                JOptionPane.showMessageDialog(null, "GPA is Greater than 5.0");
                 level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
                
            }
            
            else{
                  model.insertRow(model.getRowCount(), new Object[]
        { 
        
         level.getSelectedItem(),
             sem.getSelectedItem(),
         gpa.getText()
        
        });
   
        level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
            }
        
        
        }
        
       
    }//GEN-LAST:event_entActionPerformed

    private void cgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgpaActionPerformed
        // TODO add your handling code here:
        if(
                model.getRowCount()==0 ||
                model.getColumnCount()==0)
        {
        
        JOptionPane.showMessageDialog(null, " Fill all Data");
        }
        else {
        
             cgpa();
        }
        
        
    }//GEN-LAST:event_cgpaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
   while(model.getRowCount() >0){
   
       for (int i =0; i<model.getRowCount(); i++){
       
           model.removeRow(i);
       
       }
       
       your_cgpa.setText(null);
   }
    }//GEN-LAST:event_resetActionPerformed

    private void gpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaActionPerformed

    private void gpaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if( level.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Level is not Selected");
        }
        
        else if(sem.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Semester is not Selected");
        }
        
        else if (gpa.getText().isEmpty()){
        
        
            JOptionPane.showMessageDialog(null, " Enter your GPA for the Semester");
        }
        
        else {
            
            double myGpa = Double.parseDouble(gpa.getText());
            
            if(myGpa >5.0){
            
                JOptionPane.showMessageDialog(null, "GPA is Greater than 5.0");
                 level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
                
            }
            
            else{
                  model.insertRow(model.getRowCount(), new Object[]
        { 
        
         level.getSelectedItem(),
             sem.getSelectedItem(),
         gpa.getText()
        
        });
   
        level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
            }
        
        
        }
        }
        
    }//GEN-LAST:event_gpaKeyPressed

    private void entKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if( level.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Level is not Selected");
        }
        
        else if(sem.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Semester is not Selected");
        }
        
        else if (gpa.getText().isEmpty()){
        
        
            JOptionPane.showMessageDialog(null, " Enter your GPA for the Semester");
        }
        
        else {
            
            double myGpa = Double.parseDouble(gpa.getText());
            
            if(myGpa >5.0){
            
                JOptionPane.showMessageDialog(null, "GPA is Greater than 5.0");
                 level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
                
            }
            
            else{
                  model.insertRow(model.getRowCount(), new Object[]
        { 
        
         level.getSelectedItem(),
             sem.getSelectedItem(),
         gpa.getText()
        
        });
   
        level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
            }
        
        
        }
        }
    }//GEN-LAST:event_entKeyPressed

    private void semKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semKeyPressed
        // TODO add your handling code here:
        
          if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
             if( level.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Level is not Selected");
        }
        
        else if(sem.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Semester is not Selected");
        }
        
        else if (gpa.getText().isEmpty()){
        
        
            JOptionPane.showMessageDialog(null, " Enter your GPA for the Semester");
        }
        
        else {
            
            double myGpa = Double.parseDouble(gpa.getText());
            
            if(myGpa >5.0){
            
              JOptionPane.showMessageDialog(null, "GPA is Greater than 5.0");
                 level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
                
            }
            
            else{
                  model.insertRow(model.getRowCount(), new Object[]
        { 
        
         level.getSelectedItem(),
             sem.getSelectedItem(),
         gpa.getText()
        
        });
   
        level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
            }
        
        
        }
        }
    }//GEN-LAST:event_semKeyPressed

    private void levelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_levelKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
        
            
        if( level.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Level is not Selected");
        }
        
        else if(sem.getSelectedItem().equals("Choose one..."))
        {
        
            JOptionPane.showMessageDialog(null, " Semester is not Selected");
        }
        
        else if (gpa.getText().isEmpty()){
        
        
            JOptionPane.showMessageDialog(null, " Enter your GPA for the Semester");
        }
        
        else {
        
              model.insertRow(model.getRowCount(), new Object[]
        { 
        
         level.getSelectedItem(),
             sem.getSelectedItem(),
         gpa.getText()
        
        });
   
        level.setSelectedItem("Choose one...");
        sem.setSelectedItem("Choose one...");
        gpa.setText(null);
        }
        
       
        }
    }//GEN-LAST:event_levelKeyPressed

    private void resetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resetKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        
                     DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
   while(model.getRowCount() >0){
   
       for (int i =0; i<model.getRowCount(); i++){
       
           model.removeRow(i);
       
       }
       
       your_cgpa.setText(null);
   }
        }
    }//GEN-LAST:event_resetKeyPressed

    private void backKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            setVisible(false);
        start_Page sp = new start_Page();
        sp.setVisible(true);
            
        }
    }//GEN-LAST:event_backKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

 int row=jTable1.getSelectedRow();
            
            if(row==-1){
                
                JOptionPane.showMessageDialog(null, "No Row Selected");
            
            }
            else{
                
                 int c = JOptionPane.showConfirmDialog(null, "Do you realy wanna Delete","Delete",JOptionPane.YES_NO_OPTION);
                
                 if(c==0){
                 
                      DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        try{
        
            
            int SelectedRowIndex = jTable1.getSelectedRow();
            model.removeRow(SelectedRowIndex);
        }
        catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, e);
        }
                 }
                
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gpaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gpaKeyTyped
        // TODO add your handling code here:
        
        char check = evt.getKeyChar();
        if(
                !(Character.isDigit(check) 
                || check==KeyEvent.VK_BACK_SPACE 
                || check==KeyEvent.VK_ENTER 
                || check==KeyEvent.VK_PERIOD) ){
            
            
            evt.consume();
            JOptionPane.showMessageDialog(null, "Figures only");
        
        }
    }//GEN-LAST:event_gpaKeyTyped

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
       
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        cgpa_about cp = new cgpa_about();
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cGpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cGpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cGpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cGpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cGpa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cgpa;
    private javax.swing.JButton ent;
    private javax.swing.JTextField gpa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> level;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox<String> sem;
    private javax.swing.JLabel your_cgpa;
    // End of variables declaration//GEN-END:variables
}
